# Generated by Django 3.0.6 on 2021-08-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210803_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(null=True, upload_to='medicine_pics'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
