# Generated by Django 3.0.6 on 2021-08-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20210804_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
