# Generated by Django 3.0.6 on 2021-08-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210802_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='conatact',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
