# Generated by Django 3.0.6 on 2021-08-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210803_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, default='default_med_image.png', upload_to='medicine_pics'),
        ),
    ]
