# Generated by Django 3.0.6 on 2021-08-03 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_auto_20210803_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='disease_name',
        ),
        migrations.AddField(
            model_name='medicine',
            name='disease_name',
            field=models.ManyToManyField(blank=True, null=True, to='users.Disease'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='medicine',
            name='doctor_name',
            field=models.ManyToManyField(blank=True, null=True, to='users.Doctor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
