# Generated by Django 3.0.6 on 2021-08-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210803_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='disease_name',
            field=models.ManyToManyField(blank=True, to='users.Disease'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='doctor_name',
            field=models.ManyToManyField(blank=True, to='users.Doctor'),
        ),
    ]
