# Generated by Django 3.0.6 on 2021-08-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210803_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='disease_name',
        ),
        migrations.AddField(
            model_name='medicine',
            name='disease_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Disease'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='medicine',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Doctor'),
        ),
    ]
