# Generated by Django 3.0.6 on 2021-08-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210803_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='affected_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='onset_of_disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
