# Generated by Django 3.0.6 on 2021-08-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210803_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='schedul',
            new_name='schedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
