# Generated by Django 3.0.6 on 2021-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210803_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, upload_to='medicine_pics'),
        ),
    ]
